/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PMallocServiceImpl */

#include "common.h"

#ifndef _Included_com_intel_mnemonic_service_allocatorservice_internal_PMallocServiceImpl
#define _Included_com_intel_mnemonic_service_allocatorservice_internal_PMallocServiceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_mnemonic_service_allocatorservice_internal_PMallocServiceImpl
 * Method:    jniInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_intel_mnemonic_service_allocatorservice_internal_PMallocServiceImpl_jniInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_intel_mnemonic_service_allocatorservice_internal_PMallocServiceImpl
 * Method:    jniTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_mnemonic_service_allocatorservice_internal_PMallocServiceImpl_jniTerm
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
