markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/apache/incubator-metron
destination: target
exclude: [BUILD.md, Gemfile*]
keep_files: [.git]
highlight_color: "#199acf"

collections:
  docs:
    output: true
