/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_mnemonic_service_allocatorservice_internal_VMemServiceImpl */

#include "common.h"

#ifndef _Included_com_intel_mnemonic_service_allocatorservice_internal_VMemServiceImpl
#define _Included_com_intel_mnemonic_service_allocatorservice_internal_VMemServiceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_mnemonic_service_allocatorservice_internal_VMemServiceImpl
 * Method:    jniInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_intel_mnemonic_service_allocatorservice_internal_VMemServiceImpl_jniInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_intel_mnemonic_service_allocatorservice_internal_VMemServiceImpl
 * Method:    jniTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_mnemonic_service_allocatorservice_internal_VMemServiceImpl_jniTerm
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
