/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_bigdatamem_BigDataMemAllocator*/

#include "common.h"

#ifndef _Included_com_intel_bigmem_BigDataMemAllocator
#define _Included_com_intel_bigmem_BigDataMemAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_bigdatamem_BigDataMemAllocator
 * Method:    jniInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_intel_bigdatamem_BigDataMemAllocator_jniInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_intel_bigdatamem_BigDataMemAllocator
 * Method:    jniTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_bigdatamem_BigDataMemDataAllocator_jniTerm
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
