/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BigDataPMemAllocator*/

#include "common.h"

#ifndef _Included_com_intel_bigmem_BigDataPMemAllocator
#define _Included_com_intel_bigmem_BigDataPMemAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BigDataPMemAllocator
 * Method:    jniInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_intel_bigdatamem_BigDataPMemAllocator_jniInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_intel_bigdatamem_BigDataPMemAllocator
 * Method:    jniTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_bigdatamem_BigDataPMemDataAllocator_jniTerm
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
